---
driver:
  name: dokken

transport:
  name: dokken

provisioner:
  name: dokken

verifier:
  name: inspec

platforms:
- name: ubuntu-16
  driver:
    image: dokken/ubuntu-16.04
    privileged: true
    pid_one_command: /lib/systemd/systemd
    volumes:
    - /sys/fs/cgroup:/sys/fs/cgroup:ro # required by systemd
  run_list:
  - recipe[apt]
  attributes:
    apt:
      compile_time_update: true
- name: centos-7
  driver:
    image: dokken/centos-7
    privileged: true
    pid_one_command: /usr/lib/systemd/systemd
    volumes:
    - /sys/fs/cgroup:/sys/fs/cgroup:ro # required by systemd

suites:
  - name: archiveinterface
    run_list:
      - recipe[unit::archiveinterface]
  - name: cart
    run_list:
      - recipe[unit::cart]
  - name: metadata
    run_list:
      - recipe[unit::metadata]
  - name: policy
    run_list:
      - recipe[unit::policy]
  - name: uniqueid
    run_list:
      - recipe[unit::uniqueid]
  - name: proxy
    run_list:
      - recipe[unit::proxy]
  - name: ingest
    run_list:
      - recipe[unit::ingest]
  - name: uploader
    run_list:
      - recipe[unit::uploader]
  - name: uploadercli
    run_list:
      - recipe[unit::uploadercli]
  - name: notifications
    run_list:
      - recipe[unit::notify]
  - name: wrapper-archiveinterface
    run_list:
      - recipe[pacifica::archiveinterface]
  - name: wrapper-cart
    run_list:
      - recipe[unit::cart_dependencies]
      - recipe[pacifica::cartfrontend]
      - recipe[pacifica::cartbackend]
  - name: wrapper-ingest
    run_list:
      - recipe[unit::ingest_dependencies]
      - recipe[pacifica::ingestfrontend]
      - recipe[pacifica::ingestbackend]
  - name: wrapper-metadata
    run_list:
      - recipe[unit::metadata_dependencies]
      - recipe[pacifica::metadatad]
  - name: wrapper-policy
    run_list:
      - recipe[unit::policy_dependencies]
      - recipe[pacifica::policy]
  - name: wrapper-proxy
    run_list:
      - recipe[unit::proxy_dependencies]
      - recipe[pacifica::proxy]
  - name: wrapper-uniqueid
    run_list:
      - recipe[unit::uniqueid_dependencies]
      - recipe[pacifica::uniqueid]
  - name: wrapper-uploader
    run_list:
      - recipe[pacifica::uploader]
  - name: wrapper-uploadercli
    run_list:
      - recipe[pacifica::uploadercli]
  - name: wrapper-notifications
    run_list:
      - recipe[unit::notify_dependencies]
      - recipe[pacifica::notifyfrontend]
      - recipe[pacifica::notifybackend]
